### ISSUE TITLE
Error building vue43

### ISSUE THREAD

**Issue by 11philip22** [EVE-Tools/element43#55]
Hi,
When i try to build the docker image i get this error:
````
ERROR in /vue43/components/Search.vue.ts
[tsl] ERROR in /vue43/components/Search.vue.ts(63,7)
      TS2322: Type 'string | (string | null)[]' is not assignable to type 'string'.
  Type '(string | null)[]' is not assignable to type 'string'.

ERROR in ./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib??ref--6-2!./node_modules/stylus-loader??ref--6-3!./stylus/main.styl
Module build failed: Error: /vue43/node_modules/vuetify/src/stylus/components/_calendar-daily.styl:5:40
   1| @import '../bootstrap'
   2| @import '../theme'
   3|
   4| v-calendar-daily($material)
   5|   background-color: $material.calendar.background-color
---------------------------------------------^
   6|   .v-calendar-daily__intervals-head
   7|     border-right: $material.calendar.line-color 1px solid;
   8|   .v-calendar-daily_head-day

$material.calendar has no property .background-color
    at v-calendar-daily() (/vue43/node_modules/vuetify/src/stylus/components/_calendar-daily.styl:5:1)
    at ".theme--dark.v-calendar-daily" (/vue43/node_modules/vuetify/src/stylus/theme.styl:13:3)
    at dark() (/vue43/node_modules/vuetify/src/stylus/theme.styl:12:1)
    at theme() (/vue43/node_modules/vuetify/src/stylus/theme.styl:4:1)

    at CachedPathEvaluator.Evaluator.visitMember (/vue43/node_modules/stylus/lib/visitor/evaluator.js:351:11)
    at CachedPathEvaluator.Visitor.visit (/vue43/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/vue43/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitExpression (/vue43/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at CachedPathEvaluator.Visitor.visit (/vue43/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/vue43/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitExpression (/vue43/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at CachedPathEvaluator.Visitor.visit (/vue43/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/vue43/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitProperty (/vue43/node_modules/stylus/lib/visitor/evaluator.js:687:22)
    at CachedPathEvaluator.Visitor.visit (/vue43/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/vue43/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitBlock (/vue43/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at CachedPathEvaluator.Visitor.visit (/vue43/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/vue43/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.invoke (/vue43/node_modules/stylus/lib/visitor/evaluator.js:1087:17)
 @ ./stylus/main.styl 4:14-187
 @ ./store/index.ts
 @ ./store ^\.\/(?!-)[^.]+\.(js|ts)$
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js

 ERROR

  Error: Webpack build exited with errors
````
I try to run the services using docker-compose. Here is my docker-compose.yml:
````yml
version : "3.7"

services:  
  vue:
    build: https://github.com/EVE-Tools/vue43.git
    container_name: vue43
    restart: unless-stopped

  esi-markets:
    build: https://github.com/EVE-Tools/esi-markets.git
    container_name: esi-markets
    environment:
      - REFRESH_TOKEN=
      - CLIENT_ID=
      - SECRET_KEY=
      - GRPC_HOST=43000
    networks:
      - gateway
    restart: unless-stopped

  static-data:
    build: https://github.com/EVE-Tools/static-data.git
    container_name: static-data
    environment:
      - LOG_LEVEL=info
      - PORT=43000
      - DB_PATH=static-data.db
      - ESI_HOST=esi.tech.ccp.is
      - STRUCTURE_HUNT_HOST=stop.hammerti.me.uk
      - DISABLE_TLS=false
    networks:
      - gateway
    restart: unless-stopped

  top-stations:
    build: https://github.com/EVE-Tools/top-stations.git
    container_name: top-stations
    environment:
      - CRON=@hourly
      - DB_PATH=/data/top-stations.db
      - LOG_LEVEL=info
      - ESI_MARKETS_HOST=esi-markets:43000
      - PORT=43000
    networks:
      - gateway
    restart: unless-stopped

  market-stats:
    build: https://github.com/EVE-Tools/market-stats.git
    container_name: market-stats
    environment:
      - SEED_DB=false
      - CRON=0 52 * * *
      - LOG_LEVEL=info
      - POSTGRES_URL=postgres://market-stats@localhost:5432/market-stats?sslmode=disable
      - PORT=43000
    networks:
      - gateway
    restart: unless-stopped

  jumpgate:
    build: https://github.com/EVE-Tools/jumpgate.git
    container_name: jumpgate
    environment:
      - LOG_LEVEL=
      - LISTEN_HOST=:8000
      - ESI_MARKETS_HOST=esi-markets:43000
      - MARKET_STATS_HOST=market-stats:43000
      - STATIC_DATA_HOST=static-data:43000
      - TOP_STATIONS_HOST=top-stations:43000
    ports:
      - 8000:8000
    restart: unless-stopped

networks:
  gateway:
````
